### ISSUE TITLE
Record of pixie16 repo issues. 

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass#123]
_From @spaulaus on February 26, 2018 11:31_

# Description
I needed to keep a record of all the issues in the original repositories. Many of them are still things that we need to address. 

# pixie16/paass
- [x] [pixie16/paass#301](https://github.com/pixie16/paass/issues/301)
- [x] [pixie16/paass#294](https://github.com/pixie16/paass/issues/294)
- [x] [pixie16/paass#293](https://github.com/pixie16/paass/issues/293)
- [x] [pixie16/paass#287](https://github.com/pixie16/paass/issues/287)
- [x] [pixie16/paass#286](https://github.com/pixie16/paass/issues/286)
- [x] [pixie16/paass#270](https://github.com/pixie16/paass/issues/270)
- [x] [pixie16/paass#144](https://github.com/pixie16/paass/issues/144)
- [x] [pixie16/paass#143](https://github.com/pixie16/paass/issues/143)
- [x] [pixie16/paass#14](https://github.com/pixie16/paass/issues/14)
- [x] [pixie16/paass#7](https://github.com/pixie16/paass/issues/7)

# pixie16/pixie_scan
- [x] [pixie16/pixie_scan#27](https://github.com/pixie16/pixie_scan/issues/27)
- [x] [pixie16/pixie_scan#23](https://github.com/pixie16/pixie_scan/issues/23)
- [x] [pixie16/pixie_scan#20](https://github.com/pixie16/pixie_scan/issues/20)
- [x] [pixie16/pixie_scan#19](https://github.com/pixie16/pixie_scan/issues/19)
- [x] [pixie16/pixie_scan#17](https://github.com/pixie16/pixie_scan/issues/17)
- [x] [pixie16/pixie_scan#16](https://github.com/pixie16/pixie_scan/issues/16)
- [x] [pixie16/pixie_scan#15](https://github.com/pixie16/pixie_scan/issues/15)
- [x] [pixie16/pixie_scan#14](https://github.com/pixie16/pixie_scan/issues/14)
- [ ] [pixie16/pixie_scan#13](https://github.com/pixie16/pixie_scan/issues/13)
- [ ] [pixie16/pixie_scan#12](https://github.com/pixie16/pixie_scan/issues/12)
- [ ] [pixie16/pixie_scan#11](https://github.com/pixie16/pixie_scan/issues/11)
- [ ] [pixie16/pixie_scan#8](https://github.com/pixie16/pixie_scan/issues/8)

# pixie16/PixieSuite2
- [x] [pixie16/PixieSuite2#101](https://github.com/pixie16/PixieSuite2/issues/101)

_Copied from original issue: spaulaus/paass-laughing-conqueror#123_

**Comment by spaulaus** [comment]
# Specific Comments for PAASS
## pixie16/paass#14 
This is a Won't Fix. We can just ignore it since we're using ROOT to plot now.

**Comment by spaulaus** [comment]
# Specific Comments for pixie_scan
## pixie16/pixie_scan#27
This is a Won't Fix. It was only an issue with a single data set and cannot be reproduced anymore. 

## pixie16/pixie_scan#23 
This is a Won't Fix. The histogram plotting in VandleProcessor, should not have any cuts imposed on it. That way users can view the raw histograms.

## pixie16/pixie_scan#15
This is a Won't Fix. I honestly don't see an issue with keeping SCANOR now. It's far enough separated out that it won't cause any harm.
