### ISSUE TITLE
Resolves some Housekeeping issues

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass#78]
_From @spaulaus on January 24, 2018 12:42_

This PR is focused on housekeeping tickets. Organizing our information and CMake files to ensure that everything runs smoothly. 

- [X] #71 - Made GSL required dependency since it's needed by the Acquisition Libraries
- [x] #73 - Updates readme with more accurate information about the software. 
- [X] #74 - The legacy `PAASS_UTKSCAN_*` flags have been marked as advanced. 
- [X] #77 - Fixes description for Gsl1Fitter

_Copied from original issue: spaulaus/paass-laughing-conqueror/pull/78_
