### ISSUE TITLE
Cleaning up compile requirements and some issues around HRIBF

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass#81]
_From @spaulaus on January 26, 2018 12:58_

This resolves issues

- [X] #3 - Return value from UtkScanInterface::Setup is ignored.
- [x] #28 - Now able to compile everything depending on root except RootScanner. 
- [X] #83 - Resolves issues with the scripts sometimes failing since the TravisCI's trusty update
- [X] #84 - Only require fortran if we're using HRIBF
- [X] #85 - EventReader compilation / linking issues with the `PAASS_USE_HRIBF` flag

_Copied from original issue: spaulaus/paass-laughing-conqueror/pull/81_

**Comment by spaulaus** [comment]
Looks like TravisCI has made some updates. It looks like we're going to have to update the YML at the same time as this issue. @ksmith0, can you verify that #3 is resolved while I fix the CI script?

**Comment by spaulaus** [comment]
Ha....looks like the tests don't always fail. I'll dig into the scripts a little more anyway
