### ISSUE TITLE
v2.5.0

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass#89]
_From @spaulaus on January 31, 2018 10:43_

# Release Notes
- [X] #3 - Return value from UtkScanInterface::Setup is ignored.
- [x] #28 - Now able to compile everything depending on root except RootScanner. 
- [X] #83 - Resolves issues with the scripts sometimes failing since the TravisCI's trusty update
- [X] #84 - Only require fortran if we're using HRIBF
- [X] #85 - EventReader compilation / linking issues with the `PAASS_USE_HRIBF` flag

_Copied from original issue: spaulaus/paass-laughing-conqueror/pull/89_
